### PR TITLE
add math support with katex

### PR DESCRIPTION
**Pull request by alanocallaghan**
https://github.com/carpentries/carpentries-theme/pull/13

#154

### CODE REVIEW

**Comment by alanocallaghan** [comment]
https://github.com/carpentries/carpentries-theme/pull/13

**Comment by alanocallaghan** [comment]
I'll be real I have no idea what I'm doing with katex nor with yarn/npm/etc so I'm not gonna try to do this

**Comment by alanocallaghan** [comment]
Aight I think I made it work. I have no idea how to check that the implementation in this repo is correct (?) but this is the same code that works in a remote theme or when modifying one of the local files so should be equivalent

@fmichonneau

**Comment by fmichonneau** [comment]
Thank you for spending time figuring it out. This looks good! I'll merge and add to the remote theme as well so we can test further.

**Pull request merged**
