### PR TITLE
Visually separate inline code blocks

### PR DESCRIPTION
**Pull request by maxim-belkin**
Change text color, background color and padding around inline code blocks.

### Before
before

### After
after

### CODE REVIEW

**Comment by gvwilson** [comment]
I find this kind of highlighting more distracting than useful, particularly on smaller devices - @rgaiacs and @k8hertweck, shall we put it to a vote? And @maxim-belkin, thank you for the styling - if you have a few minutes to tackle the issue of vertical spacing after list items containing multiple paragraphs, we'd be very grateful.

**Comment by rgaiacs** [comment]
> shall we put it to a vote?

I believe that this is one of the things that the new "Lesson Development" committee is going to vote on.

**Comment by maxim-belkin** [comment]
I can look into
> the issue of vertical spacing after list items containing multiple paragraphs

if someone could point me to an example of it.

As for the PR: the purpose is to provide better visual separation of the code and the text. It can be broken into changes to text and/or background color, and font boldness/style. Currently employed method is `font style' which is clean but not easy to spot.

**Comment by maxim-belkin** [comment]
related to #76

**Comment by gvwilson** [comment]
Hard to show, because we've eliminated all instances from the existing 
lesson example :-)  To re-create, paste something like this into a page:

~~~
first term
:   first paragraph of definition

second term
:   second paragraph of definition
     *   bullet list
     *   in second definition

     with another paragraph in the definition

third term
:   more text
~~~

**Comment by rgaiacs** [comment]
Tracy, Naupaka, Trever, Remi, and I approved this.

**Pull request merged**
