### PR TITLE
Upgrade bootstrap

### PR DESCRIPTION
**Pull request by fmichonneau**
This PR replaces swcarpentry/lesson-template#144 It upgrades to the latest version of bootstrap.

@jpallen I think it takes your modifications to the CSS into account.

the templates need to be updated to reflect the change in path of bootstrap.js

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@fmichonneau Thanks for this pull request.

+1 to merge this. @jpallen Could you press the Big Green Button?

> the templates need to be updated to reflect the change in path of bootstrap.js

We will update it when pulling this repo into `site`, `workshop`, `lesson`, ...

**Comment by jpallen** [comment]
My concern with this is that it still leaves the CSS in a state that can't yet be used across all site/workshop/lesson (since site isn't updated to Bootstrap 3). My previous pull requests seem discarded in this new repo, and folding them into this big Bootstrap 3 upgrade seems a shame since I purposefully tried to make the minimal changes necessary to get the CSS to be compatible.

So if the decision rests with me, I would like to see my changes included separately so that we don't lose the version of CSS which can work with site/lesson/workshop right now, and then we're not being blocked by getting everything updated to Bootstrap 3. If you just want me to hit merge, I'm happy to do that too, and we'll just spend a bit more time getting everything compatible.

**Comment by jpallen** [comment]
Actually, I just realised that https://github.com/swcarpentry/site/pull/751 was never merged, so perhaps there never was a merged version of the CSS that worked everywhere. This is confusing...

**Comment by r-gaia-cs** [comment]
@jpallen Thanks for your feedback.

> My concern with this is that it still leaves the CSS in a state that can't yet be used across all site/workshop/lesson (since site isn't updated to Bootstrap 3).

OK. We are going to wait to have a pull request ready for that ready to merge and merge both pull requests "at the same time".

> My previous pull requests seem discarded in this new repo, and folding them into this big Bootstrap 3 upgrade seems a shame since I purposefully tried to make the minimal changes necessary to get the CSS to be compatible.

I will get this repo in sync with the others.

> So if the decision rests with me, I would like to see my changes included separately so that we don't lose the version of CSS which can work with site/lesson/workshop right now, and then we're not being blocked by getting everything updated to Bootstrap 3.

:+1:

> Actually, I just realised that swcarpentry/site#751 was never merged, so perhaps there never was a merged version of the CSS that worked everywhere. This is confusing...

Sorry again for the delay.

**Comment by fmichonneau** [comment]
It seems that @jpallen and I used a different approach with slightly
different goals and it's causing some confusion.

@gwilson initial request included "(1) single swc.css file that sits
on top of a modern version of Bootstrap that provides a consistent
look and feel across all of our sites. (2) HTML tidied up to use that
CSS correctly."

My approach to this was (1) to upgrade the version of bootstrap SWC
was using, (2) to consolidate the CSS classes in a single file, (3) to
bring the necessary modifications to the lesson-template and
workshop-template, (4) to modify the HTML/CSS for the site.

With the various pull requests, we are at (3). I first wanted to make
sure that we maintained the appearance/didn't break anything with the
lesson-template and the workshop-template before tackling the website
as it seemed more complicated with potential conflicts between classes
shared by the website and the templates.

* swcarpentry/styles#3 (this PR) takes care of upgrading to bootstrap
for the styles that will be used in the future across all
repositories. This PR includes the initial modifications James started
(e.g., https://github.com/fmichonneau/styles/blob/upgrade-bootstrap/css/swc.css#L113-115)

* swcarpentry/lesson-template#145 is probably more complicated than
needed because it includes the bootstrap upgrade, but it also includes
the changes to the HTML that are needed to accommodate the upgrade.

* swcarpentry/workshop-template#147 includes the changes to the HTML
to go with the newer bootstrap. In particular, the changes include to
not rely anymore on the CSS served from the website but from the CSS
that will be included inside the folder and will allow local rendering
the page.

It seems that to move forward we need to merge this PR so we can
identify collaboratively what needs to be updated for the website and
we can divvy up the tasks. I'm open to other suggestions/approaches.

**Comment by jpallen** [comment]
> It seems that @jpallen and I used a different approach with slightly
different goals and it's causing some confusion.
> ...
> It seems that to move forward we need to merge this PR so we can
identify collaboratively what needs to be updated for the website and
we can divvy up the tasks

:+1: 

I'm unlikely to get much time to work on this in the near future anyway, so I suggest that we don't worry about the work I did and let @fmichonneau push ahead with this approach. It sounds like a solid strategy.

**Comment by jpallen** [comment]
@r-gaia-cs Shall I 'press the Big Green Button'?

**Comment by gvwilson** [comment]
+1

**Comment by r-gaia-cs** [comment]
@fmichonneau Please let me know when you rebase this pull request.

**Comment by fmichonneau** [comment]
Hi @r-gaia-cs I think this is ready to be merged. Thanks!

**Comment by r-gaia-cs** [comment]
This looks good to me for lesson-template.

@fmichonneau What I used to merge this repo into lesson-template was

~~~
$ git remote add fmichonneau-style git@github.com:fmichonneau/styles.git
$ git fetch fmichonneau-style
$ git merge fmichonneau-style/upgrade-bootstrap
$ git checkout --theirs css/swc.css css/bootstrap/bootstrap.css
$ git commit -a
~~~

I'm merging this pull request and at February 5-6 I can help to update site, workshop-template and lesson-template.

**Pull request merged**
