### PR TITLE
secure hyperlinks to pre-empt server-side HTTPS redirects

### PR DESCRIPTION
**Pull request by katrinleinweber**
as suggested in https://github.com/swcarpentry/git-novice/pull/452#issuecomment-353035014 :-)

### CODE REVIEW

**Comment by rgaiacs** [comment]
Hi @katrinleinweber, Thanks very much for the great pull request. :sparkling_heart:  Could you change `http` to `https` in https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py as well? Thanks.

**Comment by katrinleinweber** [comment]
I changed all that didn't produce a Firefox or Safari warning on manually testing their HTTPS versions. So,  https://datacarpentry.org/ and https://lists.software-carpentry.org/listinfo/discuss need some server-side attention first ;-)

**Comment by rgaiacs** [comment]
@katrinleinweber Thanks. Better was impossible. :sparkles:

**Comment by katrinleinweber** [comment]
You're welcome :-)

**Pull request merged**
