### PR TITLE
Unifying styles

### PR DESCRIPTION
**Pull request by gvwilson**
Do **NOT** merge this pull request until corresponding changes have been made in other repositories:

- [X] [Data Carpentry lesson template](https://github.com/datacarpentry/lesson-template)
- [X] [Data Carpentry workshop template](https://github.com/datacarpentry/workshop-template)
- [X] [Data Carpentry website](https://github.com/datacarpentry/datacarpentry.github.io)
- [x] [Software Carpentry lesson template](https://github.com/swcarpentry/lesson-template/pull/287)
- [x] [Software Carpentry lesson example](https://github.com/swcarpentry/lesson-example/pull/16)
- [x] [Software Carpentry workshop template](https://github.com/swcarpentry/workshop-template/pull/273)
- [x] [Software Carpentry website](https://github.com/swcarpentry/website/pull/116)

*   This pull request replaces the existing `css` folder with `_sass` and `assets` folders containing material that can be shared between all SWC and DC sites. `assets` does *not* include `assets/css/something.scss` - that is specialized for each of the downstream repositories (e.g., the Software Carpentry workshop template has its own `assets/css/swc-workshop.scss` that includes the SASS files used to style SWC workshop pages).
*   It also creates a `_includes` folder containing one Jekyll include file (to create GitHub ribbons) - we will try to move more common material into this folder as time goes on.
*   The `tools` folder is renamed `bin` (in keeping with Unix convention).  Tools shared by multiple sites will be placed here.

### CODE REVIEW

**Comment by wking** [comment]
I'd like to see the local images that this PR is bringing in, to avoid
problems like the security warning [1]:

  Connection is Not Secure

  Parts of this page are not secure (such as images).

caused by the request for [2].  That sort of external image is also
vulnerable to link rot, and makes local testing hard without a network
connection.  For example, repo-local assets would let us role out
changes like this more gradually, instead of the flag-day suggested in
this PR for throwing over all the repositories at once.

There's a ‘help-wanted’ label here, but I'm not sure what sort of help
you're looking for.

  $ git diff --shortstat origin/master..origin/pr/37
   195 files changed, 22230 insertions(+), 21883 deletions(-)

is more than I can comprehend for review ;).

Cherry-picking a single file, I looked at bin/catalog.py for a bit,
but I can't figure out what it does, and it doesn't seem to be
referenced from a Makefile or other docs.

Anyhow, let me know what needs to happen so we can get this (or
something that gets repo-local assets in workshop-template) landed.

[1]: https://swcarpentry.github.io/workshop-template/
[2]: http://software-carpentry.org/img/software-carpentry-banner.png

**Comment by rgaiacs** [comment]
+1 to not have the 

>  Connection is Not Secure
>
>Parts of this page are not secure (such as images).

even if this means copy this repository into others.

**Comment by rgaiacs** [comment]
@gvwilson Can we merge this? What is the workflow? Can we have a call to talk about this?

**Comment by gvwilson** [comment]
Happy to chat on Tuesday (Monday's a holiday).  When's good for you?

**Comment by wking** [comment]
On Thu, Jun 16, 2016 at 06:12:09AM -0700, Greg Wilson wrote:
> Closed #37.

Was this replaced by a different PR?  Should I file a new one to get
local images [1]?

[1]: https://github.com/swcarpentry/styles/pull/37#issuecomment-199913833

**Pull request closed without merging**
