### PR TITLE
Use secure links to available external sites.

### PR DESCRIPTION
**Pull request by QuLogic**
Many of these redirect automatically, too.

See swcarpentry/workshop-template#312

### CODE REVIEW

**Comment by rgaiacs** [comment]
This is from Bootstrap. We shouldn't change them.

**Comment by QuLogic** [comment]
Sure, you can ignore the Bootstrap stuff; they're just comments. But `slideshow.css` and `swc.css` are not from Bootstrap. The links will cause mixed content warnings, or be ignored entirely.

**Comment by rgaiacs** [comment]
@QuLogic only `css/slideshow.css` will cause content warnings. And slides were or will be deprecated.

**Comment by wking** [comment]
On Sat, Mar 26, 2016 at 11:25:44AM -0700, Raniere Silva wrote:
> And slides were or will be deprecated.

I vaguely remember discussion (from January?) about reviving slides
for showing explanatory graphics when a second projector is available
(with the main projector still being used for live coding).  If I can
dig up a reference, I'll post it here.

**Pull request closed without merging**
